version: '3.8'

services:
  server:
    build: ./server
    container_name: mini-platform-server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:yourpassword@db:5432/mydatabase
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: