"""add status to Video table 

Revision ID: f29bd87fec37
Revises: 
Create Date: 2025-05-21 16:35:04.020095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29bd87fec37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Athlete_id', table_name='Athlete')
    op.drop_index('ix_Athlete_name', table_name='Athlete')
    op.drop_index('ix_Athlete_sport', table_name='Athlete')
    op.drop_index('ix_AthleteVideoTag_id', table_name='AthleteVideoTag')
    op.add_column('Video', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('Video', 'path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_Video_filename', table_name='Video')
    op.drop_index('ix_Video_id', table_name='Video')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Video_id', 'Video', ['id'], unique=False)
    op.create_index('ix_Video_filename', 'Video', ['filename'], unique=True)
    op.alter_column('Video', 'path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('Video', 'status')
    op.create_index('ix_AthleteVideoTag_id', 'AthleteVideoTag', ['id'], unique=False)
    op.create_index('ix_Athlete_sport', 'Athlete', ['sport'], unique=False)
    op.create_index('ix_Athlete_name', 'Athlete', ['name'], unique=False)
    op.create_index('ix_Athlete_id', 'Athlete', ['id'], unique=False)
    # ### end Alembic commands ###
